import './globals.css'
import { Metadata } from 'next'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >{children}
   <div className='text-center bg-black text-white'>CopyRight 2023</div>
      </body>
    </html>
  )
}
